version: "3"
services:
  decision:
    # replace username/repo:tag with your name and image details
    image: decision_service
    deploy:
      replicas: 1
      # resources:
      #   limits:
      #     cpus: "0.1"
      #     memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "9090:9090"
  loadtest:
    image: loadtest_service
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    command: go run loadtest
