version: "3"
services:
  decision:
    # replace username/repo:tag with your name and image details
    image: decision_service
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "9090:9090"
  loadtest:
    image: loadtest_service
    environment:
      DECISION_SERVICE_PROTOCOL: http
      DECISION_SERVICE_HOST: decision
      DECISION_SERVICE_PORT: 9090
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    command: go run loadtest
