version: "3"
services:
  datafile:
    image: datafile_service
    ports:
      - "2222:2222"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
  decision:
    image: decision_service
    depends_on:
      - datafile
    environment:
      - DATAFILE_SERVER=datafile:2222
    ports:
      - "9090:9090"
      - "1337:1337"
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
  loadtest:
    image: loadtest_service
    depends_on: 
      - decision
    environment:
      - DECISION_SERVER
      - DEBUG
      - RATE
      - LOADTEST_DURATION_SEC
      - TEST_NAME
      - STARTUP_DELAY=0
    deploy:
      replicas: 20
      restart_policy:
        condition: on-failure
    command: go run loadtest
