version: "3"
services:
  datafile:
    image: datafile_service
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
  decision:
    image: decision_service
    depends_on:
      - datafile
    environment:
      - DATAFILE_SERVER=datafile:2222
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
  loadtest:
    image: loadtest_service
    depends_on: 
      - decision
    environment:
      - DEBUG
      - DURATION=120
      - NUM_USERS=1000
      - RATE=25
      - STARTUP_DELAY=120
      - TARGET_SERVER=decision:9090
      - TEST_NAME=loadtest_fullstack_service_on_aws
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    command: go run loadtest
